steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/aqueous-glyph-457202-i2/flask_demo_app/flask-app:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/aqueous-glyph-457202-i2/flask_demo_app/flask-app:$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'flask-app',
        '--image',
        'us-central1-docker.pkg.dev/aqueous-glyph-457202-i2/flask_demo_app/flask-app:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--service-account',
        'cloud-run-sa@aqueous-glyph-457202-i2.iam.gserviceaccount.com'
      ]
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/aqueous-glyph-457202-i2/flask-images/flask-app:$SHORT_SHA'
